/*
 * SPDX-License-Identifier: Apache-2.0
 * Copyright Red Hat Inc. and Hibernate Authors
 */

@Library('hibernate-jenkins-pipeline-helpers') _

// NOTE: Remember to update the matrix axes below when adding/removing entries here.
// Also make sure to update the parameters in the parameters {} section of the pipeline.
Map settings() {
	switch (env.DEPENDENCY_UPDATE_NAME) {
		case 'orm':
			return [
					updateProperties: ['hibernateOrmVersion', 'hibernateOrmGradlePluginVersion'],
					dependecy: '/org/hibernate/orm/hibernate-core/'
			]
		default:
			return [:]
	}
}


pipeline {
	agent none
	triggers {
		// Run at least once per week, in case of snapshot updates.
		cron '@weekly'
	}
	parameters {
		// choice parameter doesn't have a default, but the first value should be treated as a default, if it wasn't specified manually.
		// Make sure tp update axis and settings() when adding new choice parameter.
		choice(name: 'UPDATE_JOB', choices: ['all', 'orm'], description: 'Select which update jobs to run. `All` will include all configured update jobs.')
		string(name: 'ORM_REPOSITORY', defaultValue: '', description: 'Git URL to Hibernate ORM repository. If provided, Hibernate ORM will be built locally. Works only in pair with ORM_BRANCH. Provide an http repository URL rather than an ssh one.')
		string(name: 'ORM_BRANCH', defaultValue: '', description: 'Hibernate ORM branch to build from. If provided, Hibernate ORM will be built locally. Works only in pair with ORM_REPOSITORY. Either a pull request ID or a branch name should be provided, but not both at the same time. Use branch if you want to build from a fork repository.')
		string(name: 'ORM_PULL_REQUEST_ID', defaultValue: '', description: 'Hibernate ORM pull request id to build from. If provided, Hibernate ORM will be built locally. Works only in pair with ORM_REPOSITORY. Either a pull request ID or a branch name should be provided, but not both at the same time.')
	}
	options {
		buildDiscarder logRotator(daysToKeepStr: '10', numToKeepStr: '3')
		disableConcurrentBuilds(abortPrevious: true)
		overrideIndexTriggers(false)
	}
	environment {
		TESTCONTAINERS_REUSE_ENABLE = 'true'
	}
	stages {
		// This allows testing the original (unpatched) artifacts,
		// while patching tests where necessary.
		// Especially important when testing the compatibility
		// of published artifacts with different versions of dependencies.
		stage('Pre-build original code') {
			parallel {
				stage('Build Hibernate ORM') {
					agent {
						label 'Worker&&Containers'
					}
					post {
						cleanup {
							dir('hibernate-orm-local-copy') {
								deleteDir()
							}
						}
					}
					when {
						beforeAgent true
						expression {
							return params.ORM_REPOSITORY?.trim() || params.ORM_BRANCH?.trim() || params.ORM_PULL_REQUEST_ID?.trim()
						}
					}
					tools {
						jdk 'OpenJDK 25 Latest'
					}
					steps {
						script {
							if (params.ORM_BRANCH?.trim() && params.ORM_PULL_REQUEST_ID?.trim()) {
								error "Both ORM_BRANCH and ORM_PULL_REQUEST_ID are provided. Use only one of these parameters."
							}
							if (!params.ORM_REPOSITORY?.trim() || !(params.ORM_BRANCH?.trim() || params.ORM_PULL_REQUEST_ID?.trim())) {
								error "Both ORM_REPOSITORY and either ORM_BRANCH or ORM_PULL_REQUEST_ID must be not blank if a local build of Hibernate ORM is required. Repository: [${params.ORM_REPOSITORY}], branch: [${params.ORM_BRANCH}, pull request: [${params.ORM_PULL_REQUEST_ID}]]."
							}
						}
						script {
							dir('hibernate-orm-local-copy') {
								// We may get either an http or an ssh repository URLs.
								// Since this job can work correctly only with an http URL we will try to adapt the ssh url if we spot one:
								def repositoryUrl = params.ORM_REPOSITORY ==~ /^git@github\.com:.+$/ ? params.ORM_REPOSITORY.replace("git@github.com:", "https://github.com/") : params.ORM_REPOSITORY
								if (params.ORM_BRANCH?.trim()) {
									sh "git clone ${repositoryUrl} --depth 1 --branch ${params.ORM_BRANCH} --single-branch ."
								} else {
									sh "git clone ${repositoryUrl} --depth 1 --single-branch ."
									sh "git fetch origin pull/${params.ORM_PULL_REQUEST_ID}/head:orm-branch-to-build"
									sh "git switch orm-branch-to-build"
								}

								sh "./gradlew publishToMavenLocal -x test -Dmaven.repo.local=${env.WORKSPACE_TMP}/.m2repository"
							}
							dir(env.WORKSPACE_TMP + '/.m2repository') {
								stash name: 'orm-local-build-result', includes: "org/hibernate/orm/**"
							}
						}
					}
				}
				stage('Build Hibernate Reactive') {
					agent {
						label 'Worker&&Containers'
					}
					steps {
						// The timeout cannot be in stage options, because that would
						// include the time needed to provision a node.
						script {
							sh "./gradlew publishToMavenLocal -x test -Dmaven.repo.local=${env.WORKSPACE_TMP}/.m2repository"
							dir(env.WORKSPACE_TMP + '/.m2repository') {
								stash name: 'original-build-result', includes: "org/hibernate/reactive/**"
							}
						}
					}
				}
			}
		}
		stage('Update dependency and test') {
			matrix {
				axes {
					axis {
						name 'DEPENDENCY_UPDATE_NAME'
						// NOTE: Remember to update the settings() method above when changing this.
						// And also add a new choice parameter in the parameters {} section of the pipeline
						values 'orm'
					}
				}
				stages {
					stage('Build') {
						agent {
							label 'Worker&&Containers'
						}
						when {
							beforeAgent true
							expression {
								return params.UPDATE_JOB?.trim() == 'all' || params.UPDATE_JOB?.trim() == env.DEPENDENCY_UPDATE_NAME
							}
						}
						stages {
							stage('Init') {
								steps {
									dir(env.WORKSPACE_TMP + '/.m2repository') {
										unstash name: 'original-build-result'
									}
									dir(env.WORKSPACE_TMP + '/.m2repository') {
										script{
											try {
												unstash name: 'orm-local-build-result'
											} catch (e) {
												echo 'Hibernate ORM was not built, ignoring unstash of snapshot ORM jars'
											}
										}
									}
								}
							}
							stage('Update dependency') {
								steps {
									script {
										def version = sh(
												script: "xmllint --xpath 'string(/metadata/versioning/latest)' ${env.WORKSPACE_TMP + '/.m2repository' + settings().dependecy + 'maven-metadata-local.xml'}",
												returnStdout: true
										).trim()
										echo "Found the following latest version: ${version}"

									}
								}
							}
							stage('Test') {
								post {
									cleanup {
										sh 'ci/docker-cleanup.sh'
									}
								}
								options {
									timeout(time: 1, unit: 'HOURS')
								}
								steps {
									withWorkspace {
										sh """ \
									mvn clean install -U -Pdependency-update -Pdist -Pci-build -Dsurefire.environment=${normalize(env.DEPENDENCY_UPDATE_NAME)} \
									--fail-at-end -Dno-build-cache \
									${env[qualify('ADDITIONAL_MAVEN_ARGS')]} \
								"""
									}
								}
							}
						}
					}
				}
			}
		}
	}
	post {
		always {
			notifyBuildResult maintainers: 'marko@hibernate.org'
		}
	}
}
